---
- name: update web servers
  hosts: "{{host_name}}"

  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: "{{service}}"
      state: latest
      notify:
      - restart "{{service}}"
   
  - name: Ensure apache is running
      name: "{{service}}"
      state: started

#  - name: ensure httpd is running
#    service:
#      name: "{{service}}"
#      state: started

  - name: Open port 80 for http access
    firewalld:
      service: "{{service}}"
      permanent: true
      state: enabled
